### ISSUE TITLE
wish: "undecorate" support

### ISSUE THREAD

**Issue by markstos** [dancor/wmctrl#1]
Thanks for publishing some patches to wmctrl. 

I would for wmctrl to also have the option to decorate/undecorate a window. 

There is code to do this in the "devilspie" project, located in the "set_decorations" function in src/actions.c.

Currently some wmctrl actions don't work on undecorated windows.

**Comment by dancor** [comment]
sorry for the delay.  i'm trying to contact the original author (tripie@cpan.org, tomas@styblo.name) to see about reconciling our changes with the main development branch.

i haven't looked at adding this code yet.  i guess ideally there would be some lib that both projects use instead of copying it over.  i'm also not sure yet how specific the spec (http://standards.freedesktop.org/wm-spec/wm-spec-1.3.html) is about setting/unsetting decorations.

i'm not sure why undecoration would make some actions fail.  do you have a specific window manager and maybe steps to reproduce specific errors?  thanks, --dan

**Comment by dancor** [comment]
i haven't heard back from the original author.  based on feedback below from markstos, i'm going to close this for now.  i'm not certain enough that we should support it to do any work myself (heh) and would rather wait at least to see if others want it, or something.

> I looked into this further and found it was an
> illusion. It turned out when I was toggling a window to be maximized and
> undecorated, it was not remaining active, but since it was a fullscreen and
> undecorated, I had no clue that it was losing its active status. By making the
> window active again, wmctrl did perform as expected, even though it was
> undecorated.
> 
> The code to handle undecorated windows appears to be only about ~20 lines > in devilspie. That seems like a relatively small amount to borrow.
> I don't think decorating/undecorating is supported in the spec, and devilspie
> doesn't try to use it. It uses both Openbox and "Motif" hints depending on the
> context. I can understand if you don't want to go down the road of starting to
> support features which are not in the spec.
> 
> Now that I've figured out the fullscreen issue, I think I have less less need
> for decoration support. I'm using "maximus" to undecorate maximized
> applications, and that works well enough for me now.
